### ISSUE TITLE
Create factorial skeleton file

### ISSUE THREAD

**Issue by wtmo-dev** [KeaDoRi/subject1#1]
## Description
create skeleton factorial.py

## Tasks
- [ ] 1. Create factorial.py with OOP style(class) : factorial.py를 만들어서 class로 정의하세요
- [ ] 2. Add \_\_init__ : class의 \_\_init__ 함수를 만들어 주세요
- [ ] 3. Add definition of "start" : class를 작동시킬 함수를 만들어주세요

## References
[ref.1](link)

**Comment by wtmo-dev** [comment]
merge done with eunzzae's code
