### ISSUE TITLE
update factorial.py

### ISSUE THREAD

**Issue by wtmo-dev** [KeaDoRi/subject1#2]
## Description
update factorial.py could be work

## Tasks
- [ ] 1. add docstring for start function : 작동시키는 함수의 docstring을 작성해보세요.
- [ ] 2. add \_\_init__ items : \_\_init__에 필요한 사항들을 채워 넣어 보세요.
- [ ] 3. make it work with start function : start함수가 정상작동하게 해주세요.

## References
[ref.1](link)
