### ISSUE TITLE
create linear regressor with ipython

### ISSUE THREAD

**Issue by wtmo-dev** [KeaDoRi/subject1#4]
## Description
create linear regressor file with ipython

## Tasks
- [ ] 1. create li_reg.ipynb : li_reg.ipynb을 만들어 주세요.
- [ ] 2. add cancer dataset : cancer dataset을 불러와주세요.
- [ ] 3. EDA with cancer dataset : cancer dataset을 이용하여 EDA를 진행해주세요.
- [ ] 4. make base model : linear regressor를 이용하여 베이스 모델을 만들어주세요.

## References
[cancer dataset](https://data.world/nrippner/cancer-linear-regression-model-tutorial)
