### ISSUE TITLE
make li_reg.ipynb work better then before

### ISSUE THREAD

**Issue by wtmo-dev** [KeaDoRi/subject1#5]
## Description
make li_reg.ipynb work better then before(mse rate up)

## Tasks
- [ ] 1. try Ridge : li_reg.ipynb에 Ridge를 활용해보세요.
- [ ] 2. try Lasso : li_reg.ipynb에 Lasso를 활용해보세요.
- [ ] 3. try ElasticNet : li_reg.ipynb에 ElasticNet을 활용해보세요.

## References
[ref.1](link)
